catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:slug>/', views.category, name='category'),
    path('produtos/<slug:slug>/', views.product, name='product'),
]

checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'
urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/', views.create_cart_item, name='create_cart_item'),
    path('carrinho/', views.cart_item,  name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro', views.pagseguro_view, name='pagseguro_view'),
    path('notificacoes/pagseguro/', views.pagseguro_notification, name='pagseguro_notification')
]

devstore/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('compras/', include('checkout.urls', namespace='checkout'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum
from pagseguro import PagSeguro

from catalog.models import Product, Size

# Create your models here.
class CartItemManager(models.Manager):

    def add_item(self, cart_key, product, value_size):
        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity = cart_item.quantity + 1
            print(cart_item.quantity)
            cart_item.save()
        else:
            created = True
            if product.sale:
                cart_item = CartItem.objects.create(cart_key=cart_key, product=product, price=product.sale, size=value_size)
            else:
                cart_item = CartItem.objects.create(cart_key=cart_key, product=product, price=product.price, size=value_size)
        return cart_item, created

class CartItem(models.Model):

    cart_key = models.CharField('Chave do Carrinho', max_length=40, db_index=True)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    size = models.CharField('Tamanho', max_length=3, null=True)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)

    def __str__(self):
        return '{} [{}]'.format(self.product, self.quantity)

class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, quantity=cart_item.quantity, product=cart_item.product, price=cart_item.price, size=cart_item.size
            )
        return order

class Order(models.Model):
    
    STATUS_CHOICES = (
        (1, 'Aguardando pagamento'),
        (2, 'Em análise'),
        (3, 'Paga'),
        (4, 'Disponível'),
        (5, 'Em disputa'),
        (6, 'Devolvida'),
        (7, 'Cancelada'),
    )
    PAYMENT_OPTION_CHOICES = (
        ('pagseguro', 'PagSeguro'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE)
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=1, blank=True)
    payment_option = models.CharField('Opção de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20, default='pagseguro')
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    def products(self):
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)

    def sub_total(self):
        aggregate_queryset = self.items.aggregate(
            sub_total=models.Sum(
                models.F('price') * models.F('quantity'), output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['sub_total']

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=models.Sum(
                models.F('price') * models.F('quantity'), output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['total']

    def pagseguro_update_status(self, status):
        if status == '1':
            self.status = 1
        elif status == '2':
            self.status = 2
        elif status == '3':
            self.status = 3
        elif status == '4':
            self.status = 4
        elif status == '5':
            self.status = 5
        elif status == '6':
            self.status = 6
        elif status == '7':
            self.status = 7
        self.save()

    def pagseguro(self):
        self.payment_option = 'pagseguro'
        self.save()
        if settings.PAGSEGURO_SANDBOX:
            pg = PagSeguro(
                email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
                config={'sandbox': settings.PAGSEGURO_SANDBOX}
            )
        else:
            pg = PagSeguro(
                email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN
            )
        pg.sender = {
            'email': self.user.email
        }
        pg.reference_prefix = None
        pg.shipping = None
        pg.reference = self.pk
        for item in self.items.all():
            pg.items.append(
                {
                    'id': item.product.pk,
                    'description': item.product.name,
                    'quantity': item.quantity,
                    'amount': '%.2f' % item.price
                }
            )
        return pg

class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    size = models.CharField('Tamanho', max_length=3, null=True)

    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens dos Pedidos'

    def __str__(self):
        return '[{}] {}'.format(self.order, self.product)

def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()

models.signals.post_save.connect(
    post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item'
)

checkout/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import RedirectView, TemplateView
from django.forms import modelformset_factory
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from pagseguro import PagSeguro

from catalog.models import Product
from .models import CartItem, Order

# Create your views here.
class CreateCartItemView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        value_size = self.request.POST.get("value_size")
        cart_item, created = CartItem.objects.add_item(self.request.session.session_key, product, value_size)
        if created:
            messages.success(self.request, 'Produto adicionado com sucesso.')
        else:
            messages.success(self.request, 'Produto atualizado com sucesso.')
        return reverse('checkout:cart_item')

class CartItemView(TemplateView):

    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(CartItem, fields=('quantity',), can_delete=True, extra=0)
        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key)
                )
            else:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())
        return formset

    def get_value_total(self):
        session_key = self.request.session.session_key
        queryset=CartItem.objects.filter(cart_key=session_key)
        value = 0
        for total in queryset:
            value = value + (total.quantity * total.price)
        return value

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        value = self.get_value_total()
        context['total'] = value
        return context
    
    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso.')
            context['formset'] = self.get_formset(clear=True)
        value = self.get_value_total()
        context['total'] = value
        return self.render_to_response(context)

class CheckoutView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(user=request.user, cart_items=cart_items)
            cart_items.delete()
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response

class PagSeguroView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(Order.objects.filter(user=self.request.user), pk=order_pk)
        pg = order.pagseguro()
        pg.redirect_url = self.request.build_absolute_uri(
            reverse('accounts:order_detail', args=[order.pk])
        )
        pg.notification_url = self.request.build_absolute_uri(
            reverse('checkout:pagseguro_notification')
        )
        response = pg.checkout()
        return response.payment_url

@csrf_exempt
def pagseguro_notification(request):
    notification_code = request.POST.get('notificationCode', None)
    if notification_code:
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN, 
            config={'sandbox': settings.PAGSEGURO_SANDBOX}
        )
        notification_data - pg.check_notification(notification_code)
        status = notification_data.status
        reference = notification_data.reference
        try:
            order = Order.objects.get(pk=reference)
        except Order.DoesNotExist:
            pass
        else:
            order.pagseguro_update_status(status)
    return HttpResponse('OK')

create_cart_item = CreateCartItemView.as_view()
cart_item = CartItemView.as_view()
checkout = CheckoutView.as_view()
pagseguro_view = PagSeguroView.as_view()

checkout/templates/checkout/cart.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% load calculation %}

{% block title %}Carrinho de Compras | {{ block.super }}{% endblock  %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item active" aria-current="page">Carrinho de Compras</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Carrinho de Compras</h1>
    </div> 
    <div class="div-distance">
        <form method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            {% if formset.forms %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Produto</th>
                        <th scope="col">Preço Unitário</th>
                        <th scope="col">Quantidade</th>
                        <th scope="col">Sub Total</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for form in formset %}
                    <tr>
                        <td>
                            <div class="d-flex flex-row bd-highlight mb-3">
                                <div class="p-2 bd-highlight">
                                    <img class="card-img-checkout rounded-0" src="{{ form.instance.product.image.url }}" alt="Product image">
                                </div>
                                <div class="p-2 bd-highlight">
                                    <a class="page-item" href="{{ form.instance.product.get_absolute_url }}">{{ form.instance.product }}</a>
                                    <p class="mb-0">Categoria: {{ form.instance.product.category }}</p>
                                    {% if form.instance.size %}
                                    <p class="mb-0">Tamanho - {{ form.instance.size }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </td>
                        <td>
                            {% if form.instance.product.sale %}
                            <p>R$ {{ form.instance.price }}</p>
                            {% else %}
                            <p>R$ {{ form.instance.price }}</p>
                            {% endif %}
                        </td>
                        <td>{% render_field form.quantity class='form-control' %}</td>
                        <td>R$ {% multiply form.instance.quantity form.instance.price %}</td>
                        <td>
                            <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="button-icon"><i class="fas fa-trash-alt"></i></button>
                            {{ form.id }}
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3"></td>
                        <td><span class="span-item">Subtotal:</span></td>
                        <td>R$ {{ total }}</td>
                    </tr>
                    <tr>
                        <td colspan="3"></td>
                        <td><span class="span-item">Frete:</span></td>
                        <td>Grátis</td>
                    </tr>
                    <tr>
                        <td colspan="3"></td>
                        <td><span class="span-item">Total:</span></td>
                        <td>R$ {{ total }}</td>
                    </tr>
                </tbody>
            </table>
            <div class="d-flex justify-content-end">
                <a href="{% url 'catalog:product_list' %}" class="button mr-2">Continuar Comprando</a>
                <button type="submit" class="button mr-2">Atualizar Carrinho</button>
                <a href="{% url 'checkout:checkout' %}" class="button">Finalizar Compra</a>
            </div>
            {% else %}
            <div class="d-flex justify-content-center">
                <h3 class="title-h3">Carrinho vázio.</h3>
            </div>
            <div class="d-flex justify-content-center link-item">
                <a href="{% url 'catalog:product_list' %}">Continuar Comprando</a>
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% load static %}

{% load widget_tweaks %}

{% load calculation %}

{% block title %}Finalização da Compra | {{ block.super }}{% endblock  %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item"><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
        <li class="breadcrumb-item active" aria-current="page">Finalização da Compra</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Finalização da Compra</h1>
    </div> 
    <div class="div-distance">
        <div class="alert alert-warning">
            <span class="span-item">Redirecionando!</span> Você será redirecionado para o PagSeguro em 0 segundos ou se preferir, 
            <a href="{% url 'checkout:pagseguro_view' order.pk %}"><span class="span-item">clique aqui</span></a>.
        </div>
        <div class="row div-distance">
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Dados do pedido #{{ order.pk }}</h5>
                </div>
                <div class="link-item">
                    <p class="mb-1"><span class="span-item">Situação: </span>{{ order.get_status_display }}</p>
                    <p class="mb-1"><span class="span-item">Data: </span>{{ order.created|date:"d/m/Y" }}</p>
                </div>
            </div>
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Dados pessoais</h5>
                </div>
                <div class="link-item">
                    <p class="mb-1"><span class="span-item">Nome: </span>{{ user.name }}</p>
                    <p class="mb-1"><span class="span-item">CPF: </span>{{ user.cpf }}</p>
                    {% if user.street %}
                    <p class="mb-1"><span class="span-item">Endereço: </span>{{ user.street }}, {{ user.number }}, {{ user.complement }}, 
                        {{ user.district }}, {{ user.city }} / {{ user.state }}, {{ user.zipcode }}</p>
                    {% else %}
                    <p class="text-justify">Você não possui um endereço de entrega e cobrança.</p>
                    {% endif %} 
                </div>
            </div>
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Pagamento</h5>
                </div>
                <div>
                    <img class="pagseguro-logo" src="{% static 'img/pagseguro-logo.png' %}" alt="Pagseguro">
                </div>
            </div>
        </div>
        <div class="row div-distance">
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Itens do pedido</h5>
                </div>
                <div class="div-distance">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Produto</th>
                                <th scope="col">Preço Unitário</th>
                                <th scope="col">Quantidade</th>
                                <th scope="col">Sub Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in order.items.all %}
                            <tr>
                                <td>
                                    <div class="d-flex flex-row bd-highlight mb-3">
                                        <div class="p-2 bd-highlight">
                                            <img class="card-img-checkout rounded-0" src="{{ order.product.image.url }}" alt="Product image">
                                        </div>
                                        <div class="p-2 bd-highlight">
                                            <a class="page-item" href="{{ form.instance.product.get_absolute_url }}">{{ order.product }}</a>
                                            <p>Tamanho - {{ order.size }}</p>
                                        </div>
                                    </div>
                                </td>
                                <td>R$ {{ order.price }}</td>
                                <td>{{ order.quantity }}</td>
                                <td>R$ {% multiply order.quantity order.price %}</td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="2"></td>
                                <td><span class="span-item">Subtotal:</span></td>
                                <td>R$ {{ order.sub_total }}</td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td><span class="span-item">Frete:</span></td>
                                <td>Grátis</td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td><span class="span-item">Total:</span></td>
                                <td>R$ {{ order.total }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$(window.document.location).attr('href', "{% url 'checkout:pagseguro_view' order.pk %}")
</script>
{% endblock %}