accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('entrar/', LoginView.as_view(),  name='login'),
    path('sair/', LogoutView.as_view(), name='logout'),
    path('registro/', views.register, name='register'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-endereco/', views.update_address, name='update_address'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('recuperar-senha/', PasswordResetView.as_view(), name='password_reset'),
    path('recuperar-senha/enviado/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('recuperar-senha/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('recuperar-senha/completo/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('meus-pedidos/', views.order_list, name='order_list'),
    path('meus-pedidos/<int:pk>/', views.order_detail, name='order_detail')
]

catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:slug>/', views.category, name='category'),
    path('produtos/<slug:slug>/', views.product, name='product'),
]

devstore/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('compras/', include('checkout.urls', namespace='checkout'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from localflavor.br.br_states import STATE_CHOICES
import re

# Create your views here.
class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = (
        ('m', 'Masculino'),
        ('f', 'Feminino'),
    )
    username = models.CharField('Usuário', max_length=30, unique=True, validators=[
        validators.RegexValidator(re.compile('^[\w.@+-]+$'), 'Informe um nome de usuário válido. Este valor deve conter apenas letras, números e os caracteres: @/./+/-/_.', 'invalid')
    ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma')
    name = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail', unique=True)
    cpf = models.CharField('CPF', max_length=14)
    gender = models.CharField('Sexo', max_length=1, choices=GENDER_CHOICES)
    telephone = models.CharField('Telefone', max_length=15)
    birth = models.DateField('Data de Nascimento')
    street = models.CharField('Rua', max_length=100, blank=True)
    number = models.CharField('Número', max_length=5, blank=True)
    complement = models.CharField('Complemento', max_length=50, blank=True)
    district = models.CharField('Bairro', max_length=50, blank=True)
    city = models.CharField('Cidade', max_length=100, blank=True)
    state = models.CharField('Estado', max_length=2, choices=STATE_CHOICES, blank=True)
    zipcode = models.CharField('CEP', max_length=9, blank=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

checkout/models.py
from django.db import models
from django.conf import settings
from django.db.models import Sum
from pagseguro import PagSeguro

from catalog.models import Product, Size

# Create your models here.
class CartItemManager(models.Manager):

    def add_item(self, cart_key, product, value_size):
        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity = cart_item.quantity + 1
            print(cart_item.quantity)
            cart_item.save()
        else:
            created = True
            if product.sale:
                cart_item = CartItem.objects.create(cart_key=cart_key, product=product, price=product.sale, size=value_size)
            else:
                cart_item = CartItem.objects.create(cart_key=cart_key, product=product, price=product.price, size=value_size)
        return cart_item, created

class CartItem(models.Model):

    cart_key = models.CharField('Chave do Carrinho', max_length=40, db_index=True)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    size = models.CharField('Tamanho', max_length=3, null=True)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)

    def __str__(self):
        return '{} [{}]'.format(self.product, self.quantity)

class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, quantity=cart_item.quantity, product=cart_item.product, price=cart_item.price, size=cart_item.size
            )
        return order

class Order(models.Model):
    
    STATUS_CHOICES = (
        (1, 'Aguardando pagamento'),
        (2, 'Em análise'),
        (3, 'Paga'),
        (4, 'Disponível'),
        (5, 'Em disputa'),
        (6, 'Devolvida'),
        (7, 'Cancelada'),
    )
    PAYMENT_OPTION_CHOICES = (
        ('pagseguro', 'PagSeguro'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE)
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=1, blank=True)
    payment_option = models.CharField('Opção de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20, default='pagseguro')
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    def products(self):
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)

    def sub_total(self):
        aggregate_queryset = self.items.aggregate(
            sub_total=models.Sum(
                models.F('price') * models.F('quantity'), output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['sub_total']

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=models.Sum(
                models.F('price') * models.F('quantity'), output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['total']

    def pagseguro_update_status(self, status):
        if status == '1':
            self.status = 1
        elif status == '2':
            self.status = 2
        elif status == '3':
            self.status = 3
        elif status == '4':
            self.status = 4
        elif status == '5':
            self.status = 5
        elif status == '6':
            self.status = 6
        elif status == '7':
            self.status = 7
        self.save()

    def pagseguro(self):
        self.payment_option = 'pagseguro'
        self.save()
        if settings.PAGSEGURO_SANDBOX:
            pg = PagSeguro(
                email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
                config={'sandbox': settings.PAGSEGURO_SANDBOX}
            )
        else:
            pg = PagSeguro(
                email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN
            )
        pg.sender = {
            'email': self.user.email
        }
        pg.reference_prefix = None
        pg.shipping = None
        pg.reference = self.pk
        for item in self.items.all():
            pg.items.append(
                {
                    'id': item.product.pk,
                    'description': item.product.name,
                    'quantity': item.quantity,
                    'amount': '%.2f' % item.price
                }
            )
        return pg

class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey('catalog.Product', verbose_name='Produto', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    size = models.CharField('Tamanho', max_length=3, null=True)

    class Meta:
        verbose_name = 'Item do Pedido'
        verbose_name_plural = 'Itens dos Pedidos'

    def __str__(self):
        return '[{}] {}'.format(self.order, self.product)

def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()

models.signals.post_save.connect(
    post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item'
)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from localflavor.br.forms import BRCPFField, BRZipCodeField

from .models import User

class UserAdminCreationForm(UserCreationForm):

    cpf = BRCPFField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'name', 'cpf', 'gender', 'telephone', 'birth']

class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, UpdateView, FormView, ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm
from checkout.models import Order

# Create your views here.
class IndexView(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/index.html'

class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')

class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email', 'cpf', 'gender', 'telephone', 'birth']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user

class UpdateAddressView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_address.html'
    fields = ['street', 'number', 'complement', 'district', 'city', 'state', 'zipcode']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user

class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)

class OrderListView(LoginRequiredMixin, ListView):

    template_name = 'accounts/order_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

class OrderDetailView(LoginRequiredMixin, DetailView):

    template_name = 'accounts/order_detail.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_address = UpdateAddressView.as_view()
update_password = UpdatePasswordView.as_view()
order_list = OrderListView.as_view()
order_detail = OrderDetailView.as_view()

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block title %}Minha Conta | {{ block.super }}{% endblock %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item active" aria-current="page">Minha Conta</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Minha conta</h1>
    </div>
    <div class="div-distance">
        <div class="page-header">
            <h3 class="title-h3">Olá, {{ user.name }}</h3>
            <p class="text-justify">Aqui é possível ver um resumo das suas atividades e atualizar suas informações.</p>
        </div>
        <div class="row div-distance">
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Dados pessoais</h5>
                </div>
                <div class="link-item">
                    {% if user %}
                    <p class="mb-1">{{ user.name }}</p>
                    <p>{{ user.email }}</p>
                    {% endif %}
                </div>
                <a class="button" href="{% url 'accounts:update_user' %}">Alterar dados</a>
                <a class="button" href="{% url 'accounts:update_password' %}">Alterar senha</a>
            </div>
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Endereço de entrega e cobrança</h5>
                </div>
                <div class="link-item">
                    {% if user.street %}
                    <p class="mb-1">{{ user.street }}, {{ user.number }}, {{ user.complement }}, {{ user.district }}</p>
                    <p>{{ user.city }}, {{ user.state }}, {{ user.zipcode }}</p>
                    {% else %}
                    <p class="text-justify">Você não possui um endereço de entrega e cobrança.</p>
                    {% endif %} 
                </div>
                <a class="button" href="{% url 'accounts:update_address' %}">Alterar endereço</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/order_detail.html
{% extends "base.html" %}

{% load calculation %}

{% block title %}Pedido #{{ order.pk }} | {{ block.super }}{% endblock %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item"><a href="{% url 'accounts:order_list' %}">Meus Pedidos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Pedido #{{ order.pk }}</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Pedido #{{ order.pk }}</h1>
    </div> 
    <div class="div-distance">
        <div class="row div-distance">
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Dados do pedido</h5>
                </div>
                <div class="link-item">
                    <p class="mb-1"><span class="span-item">Total: </span>R$ {{ order.total }}</p>
                    <p class="mb-1"><span class="span-item">Situação: </span>{{ order.get_status_display }}</p>
                    <p class="mb-1"><span class="span-item">Data: </span>{{ order.created|date:"d/m/Y H:i" }}</p>
                    <p><span class="span-item">Forma de Pagamento: </span>{{ order.get_payment_option_display }}</p>
                </div>
            </div>
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Endereço de entrega e cobrança</h5>
                </div>
                <div class="link-item">
                    <p class="mb-1"><span class="span-item">Destinatário: </span>{{ order.user.name }}</p>
                    {% if user.street %}
                    <p class="mb-1"><span class="span-item">Endereço: </span>{{ user.street }}, {{ user.number }}, {{ user.complement }}, {{ user.district }}</p>
                    <p class="mb-1"><span class="span-item">Cidade/UF: </span>{{ user.city }} / {{ user.state }}</p>
                    <p><span class="span-item">CEP: </span>{{ user.zipcode }}</p>
                    {% else %}
                    <p class="text-justify">Você não possui um endereço de entrega e cobrança.</p>
                    {% endif %} 
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="page-header">
                    <h5 class="title-h5">Itens do pedido</h5>
                </div>
                <div class="div-distance">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Produto</th>
                                <th scope="col">Preço Unitário</th>
                                <th scope="col">Quantidade</th>
                                <th scope="col">Sub Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in order.items.all %}
                            <tr>
                                <td>
                                    <div class="d-flex flex-row bd-highlight mb-3">
                                        <div class="p-2 bd-highlight">
                                            <img class="card-img-checkout rounded-0" src="{{ order.product.image.url }}" alt="Product image">
                                        </div>
                                        <div class="p-2 bd-highlight">
                                            <a class="page-item" href="{{ order.product.get_absolute_url }}">{{ order.product }}</a>
                                            <p class="mb-0">Categoria: {{ order.product.category }}</p>
                                            {% if order.size %}
                                            <p class="mb-0">Tamanho - {{ order.size }}</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                </td>
                                <td>R$ {{ order.price }}</td>
                                <td>{{ order.quantity }}</td>
                                <td>R$ {% multiply order.quantity order.price %}</td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="2"></td>
                                <td><span class="span-item">Subtotal:</span></td>
                                <td>R$ {{ order.sub_total }}</td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td><span class="span-item">Frete:</span></td>
                                <td>Grátis</td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td><span class="span-item">Total:</span></td>
                                <td>R$ {{ order.total }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/order_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}Meus Pedidos | {{ block.super }}{% endblock %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item active" aria-current="page">Meus Pedidos</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Meus Pedidos</h1>
    </div> 
    <div class="div-distance">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Produtos</th>
                    <th scope="col">Total</th>
                    <th scope="col">Situação</th>
                    <th scope="col">Data</th>
                </tr>
            </thead>
            <tbody>
                {% for order in object_list %}
                <tr>
                    <th scope="row">
                        <a class="page-item" href="{% url 'accounts:order_detail' order.pk %}">Pedido #{{ order.pk }}</a>
                    </th>
                    <td>
                        {% for product in order.products %}
                        <a class="page-item" href="{{ product.get_absolute_url }}">
                            {{ product.name }}{% if not forloop.last %}, {% endif %}
                        </a>
                        {% endfor %}
                    </td>
                    <td>R$ {{ order.total }}</td>
                    <td>{{ order.get_status_display }}</td>
                    <td>{{ order.created|date:"d/m/Y" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% pagination request paginator page_obj %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load static %}

{% load widget_tweaks %}

{% block title %}Criar Conta | {{ block.super }}{% endblock %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item active" aria-current="page">Criar Conta</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Criar Conta</h1>
    </div>
    <div class="div-distance">
        <form method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <div class="page-header">
                <h5 class="title-h5">Dados de acesso</h5>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.username.auto_id }}">{{ form.username.label }}</label>
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-4{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.password1.auto_id }}">{{ form.password1.label }}</label>
                    {% render_field form.password1 class="form-control" %}
                    {% for error in form.password1.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-4{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.password2.auto_id }}">{{ form.password2.label }}</label>
                    {% render_field form.password2 class="form-control" %}
                    {% for error in form.password2.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="page-header">
                <h5 class="title-h5">Dados pessoais</h5>
            </div>
            <div class="form-row">
                <div class="form-group col-md-7{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.name.auto_id }}">{{ form.name.label }}</label>
                    {% render_field form.name class="form-control" %}
                    {% for error in form.name.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-5{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.email.auto_id }}">{{ form.email.label }}</label>
                    {% render_field form.email class="form-control" %}
                    {% for error in form.email.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-3{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.cpf.auto_id }}">{{ form.cpf.label }}</label>
                    {% render_field form.cpf class="form-control cpf" %}
                    {% for error in form.cpf.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-3{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.gender.auto_id }}">{{ form.gender.label }}</label>
                    {% render_field form.gender class="form-control" %}
                    {% for error in form.gender.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-3{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.telephone.auto_id }}">{{ form.telephone.label }}</label>
                    {% render_field form.telephone class="form-control phone_with_ddd" %}
                    {% for error in form.telephone.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-3{% if field.errors %} has-error {% endif %}">
                    <label for="{{ form.birth.auto_id }}">{{ form.birth.label }}</label>
                    {% render_field form.birth class="form-control date" %}
                    {% for error in form.birth.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            <a class="button" href="{% url 'accounts:login' %}">Voltar</a>
            <button type="submit" class="button">Cadastrar</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Alterar Senha | {{ block.super }}{% endblock %}

{% block container %}
<div class="container div-content">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
            <li class="breadcrumb-item"><a href="{% url 'accounts:index' %}">Minha Conta</a></li>
            <li class="breadcrumb-item active" aria-current="page">Alterar Senha</li>
        </ol>
        <div class="d-flex justify-content-center">
            <h1 class="title-h1">Alterar senha</h1>
        </div>
        <div class="div-distance">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    {% for field in form %}
                    <div class="form-group col-md-4{% if field.errors %} has-error {% endif %}">
                        <label for="{{ field.auto_id }}">{{ field.label }}</label>
                        {% render_field field class="form-control" %}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
                <a class="button" href="{% url 'accounts:index' %}">Voltar</a>
                <button type="submit" class="button">Atualizar</button>
            </form>
        </div>
    </div>
{% endblock %}