accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)

from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('entrar/', LoginView.as_view(),  name='login'),
    path('sair/', LogoutView.as_view(), name='logout'),
    path('registro/', views.register, name='register'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-endereco/', views.update_address, name='update_address'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('recuperar-senha/', PasswordResetView.as_view(), name='password_reset'),
    path('recuperar-senha/enviado/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('recuperar-senha/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('recuperar-senha/completo/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('meus-pedidos/', views.order_list, name='order_list'),
    path('meus-pedidos/<int:pk>/', views.order_detail, name='order_detail')
]

catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:slug>/', views.category, name='category'),
    path('produtos/<slug:slug>/', views.product, name='product'),
]

checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'
urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/', views.create_cart_item, name='create_cart_item'),
    path('carrinho/', views.cart_item,  name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro', views.pagseguro_view, name='pagseguro_view'),
    path('notificacoes/pagseguro/', views.pagseguro_notification, name='pagseguro_notification')
]

devstore/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('compras/', include('checkout.urls', namespace='checkout'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.shortcuts import render
from django.views import generic

from catalog.models import Product

# Create your views here.
class IndexView(generic.ListView):

    model = Product
    template_name = 'index.html'
    paginate_by = 3

index = IndexView.as_view()

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'resource/bootstrap/css/bootstrap.min.css' %}" media="all">
    <title>{% block title %}Devstore | Loja para Desenvolvedores{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar bg-white fixed-top">
            <div class="container menu">
                <ul class="nav justify-content-start">
                    <li class="nav-item dropdown link-item">
                        <a class="nav-link menu-item" href="{% url 'catalog:product_list' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-bars"></i>Categorias
                        </a>
                        <div class="box-shadow dropdown-menu border-0" aria-labelledby="navbarDropdown">
                            {% for category in categories %}
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                            {% endfor %}
                        </div>
                    </li>
                </ul>
                <ul class="nav justify-content-center">
                    <p class="logo"><a href="{% url 'index' %}" title="Devstore"></a></p>
                </ul>
                <ul class="nav justify-content-end">
                    <li class="nav-item dropdown link-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link menu-item" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Olá, {{ user.get_short_name }}<i class="fas fa-angle-down"></i>
                        </a>
                        <div class="box-shadow dropdown-menu border-0" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'accounts:index' %}">Minha conta</a>
                            <a class="dropdown-item" href="{% url 'accounts:order_list' %}">Meus pedidos</a>
                            <div class="dropdown-divider"></div>
                            {% if user.is_staff %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">Painel</a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Sair</a>
                        </div>
                        {% else %}
                        <a class="nav-link menu-item" href="{% url 'accounts:login' %}">Entrar</a>
                        {% endif %}
                    </li>
                    <li class="nav-item link-item">
                        <a class="nav-link menu-item" href="{% url 'checkout:cart_item' %}"><i class="fas fa-shopping-cart"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
        {% block messages %}
            {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} messages" {% endif %}  role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endblock  %}
        </div>
        {% block container %}{% endblock %}     
    </main>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <p class="logo"><a title="Devstore"></a></p>
                    <ul class="link-item">
                        <li>
                            <p><span class="span-item">Devstore</span> © 2018</p>
                            <p>Todos os direitos reservados.</p>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5 class="title-h5">Institucional</h5>
                    <ul class="link-item">
                        <li ><a href="{% url 'index' %}">Início</a></li>
                        <li ><a href="#">Perguntas frequentes</a></li>
                        <li ><a href="#">Quem somos</a></li>
                        <li ><a href="#">Contato</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5 class="title-h5">Sac</h5>
                    <ul class="link-item">
                        <li>
                            <p>(18) 98168-8676</p>
                            <p>oficialdevstore@gmail.com</p>
                        </li>
                        <li>
                            <p><span class="span-item">Horário de Atendimento</span></p>
                            <p>Segunda a sexta, das 9h às 18h</p>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5 class="title-h5">Pagamento</h5>
                    <ul class="link-item">
                        <li>
                            <img class="pagseguro-logo" src="{% static 'img/pagseguro-logo.png' %}" alt="Pagseguro">
                        </li>
                    </ul>
                </div>
                <div class="col-md-12 py-5">
                    <div class="icon d-flex justify-content-center">
                        <a href="https://www.facebook.com/oficialdevstore/"><i class="fab fa-facebook-f fa-lg mr-md-5 mr-3 fa-2x"></i></a>
                        <a href="https://www.instagram.com/oficialdevstore/"><i class="fab fa-instagram fa-lg mr-md-5 mr-3 fa-2x"></i></a>
                        <a href="https://twitter.com/oficialdevstore/"><i class="fab fa-twitter fa-lg mr-md-5 mr-3 fa-2x"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'resource/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'resource/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'resource/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'resource/jquery-mask/jquery.mask.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

core/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block container %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/slide.png' %}" alt="First slide">
        </div>
    </div>
</div>
<div class="container div-content">
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Lançamentos</h1>
    </div>
    <div class="row div-distance">
        {% for product in product_list %}
        <div class="col-sm-6 col-lg-4 py-2">
            <div class="card h-100 border-0">
                <a href="{{ product.get_absolute_url }}">
                    {% if product.image %}
                    <img class="card-img rounded-0" src="{{ product.image.url }}" alt="Card image">
                    {% else %}
                    <img class="card-img rounded-0" src="{% static 'img/bg-product.png' %}" alt="Card image">
                    {% endif %}
                </a>
                <div class="card-body text-center">
                    <a class="card-title text-nowrap bd-highlight" style="width: 5rem;" href="{{ product.get_absolute_url }}">{{ product }}</a>
                    <div class="d-flex justify-content-around">
                        {% if product.sale %}
                        <p class="card-previous-price">R$ {{ product.price }}</p>
                        <p class="card-sale">R$ {{ product.sale }}</p>
                        {% else %}
                        <p class="card-price">R$ {{ product.price }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>  
</div>
{% endblock %}

core/templates/pagination.html
<div class="page">
    <ul class="pagination justify-content-center">
    {% for page in paginator.page_range %}
    <li {% if page_obj.number == page %} class="page-item active" {% endif %}>
        <a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a>
    </li>
    {% endfor %}
    </ul>
</div>