catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:slug>/', views.category, name='category'),
    path('produtos/<slug:slug>/', views.product, name='product'),
]

checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'
urlpatterns = [
    path('carrinho/adicionar/<slug:slug>/', views.create_cart_item, name='create_cart_item'),
    path('carrinho/', views.cart_item,  name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro', views.pagseguro_view, name='pagseguro_view'),
    path('notificacoes/pagseguro/', views.pagseguro_notification, name='pagseguro_notification')
]

devstore/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('catalogo/', include('catalog.urls', namespace='catalog')),
    path('compras/', include('checkout.urls', namespace='checkout'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})

class Size(models.Model):
    name = models.CharField('Nome', max_length=3, null=True, blank=True)

    class Meta:
        verbose_name = 'Tamanho'
        verbose_name_plural = 'Tamanhos'
        ordering = ['-name']

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria', on_delete=models.CASCADE)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    sale = models.DecimalField('Preço Promocional', decimal_places=2, max_digits=8, null=True, blank=True)
    quantity = models.PositiveIntegerField('Quantidade', default=0)
    size = models.ManyToManyField('catalog.Size', through='catalog.ProductVariation')
    image = models.FileField(upload_to='products/%Y/%m/%d/', null=True, blank=True, verbose_name='Imagem')
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['-id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

class ProductVariation(models.Model):
    size = models.ForeignKey('catalog.Size', verbose_name='Tamanho', on_delete=models.CASCADE)
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Quantidade', default=0)

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'
        ordering = ['size']

    def __str__(self):
        return self.product.name

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import ListView

from .models import Category, Product

# Create your views here.
class ProducListView(ListView):

    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'product_list'
    paginate_by = 6

class CategoryListView(ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 6

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

product_list = ProducListView.as_view()
category = CategoryListView.as_view()

def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product,
    }
    return render(request, 'catalog/product.html', context)

catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load static %}

{% load pagination %}

{% block title %}{{ current_category }} | {{ block.super }} {% endblock %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item"><a href="{% url 'catalog:product_list' %}">Produtos</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ current_category }}</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">{{ current_category }}</h1>
    </div>
    <div class="row div-distance">
        {% for product in product_list %}
        <div class="col-sm-6 col-lg-4 py-2">
            <div class="card h-100 border-0">
                <a href="{{ product.get_absolute_url }}">
                    {% if product.image %}
                    <img class="card-img rounded-0" src="{{ product.image.url }}" alt="Card image">
                    {% else %}
                    <img class="card-img rounded-0" src="{% static 'img/bg-product.png' %}" alt="Card image">
                    {% endif %}
                </a>
                <div class="card-body text-center">
                    <a class="card-title text-nowrap bd-highlight" style="width: 5rem;" href="{{ product.get_absolute_url }}">{{ product }}</a>
                    <div class="d-flex justify-content-around">
                        {% if product.sale %}
                        <p class="card-previous-price">R$ {{ product.price }}</p>
                        <p class="card-sale">R$ {{ product.sale }}</p>
                        {% else %}
                        <p class="card-price">R$ {{ product.price }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>  
    {% pagination request paginator page_obj %} 
</div>
{% endblock %}    

catalog/templates/catalog/product.html
{% extends "base.html" %}

{% load static %}

{% load widget_tweaks %}

{% block title %}{{ product }} | {{ block.super }}{% endblock %}

{% block container %}
<div class="container div-content">
    <div class="row">
        <div class="col-sm-2">
            <div class="gallery-item invisible-scrollbar">
                <a href="{{ product }}" data-toggle="tab" aria-expanded="true">
                    {% if product.image %}
                    <img class="card-img rounded-0 mb-2" src="{{ product.image.url }}" alt="Product image">
                    {% else %}
                    <img class="card-img rounded-0" src="{% static 'img/bg-product.png' %}" alt="Product image">
                    {% endif %}
                </a>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="tab-content">
                <div class="tab-pane active" id="{{ product }}">
                    <div class="profile-image">
                        {% if product.image %}
                        <img class="card-img rounded-0" src="{{ product.image.url }}" alt="Product image">
                        {% else %}
                        <img class="card-img rounded-0" src="{% static 'img/bg-product.png' %}" alt="Product image">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-5">
            <div>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'catalog:product_list' %}">Produtos</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ product }}</li>
                </ol>
            </div>
            <div> 
                <h1 class="product-title">{{ product }}</h1>
                <p>Categoria: {{ product.category }}</p>
                {% if product.sale %}
                <p class="product-previous-price">De: R$ {{ product.price }}</p>
                <p class="product-price">Por: R$ {{ product.sale }}</p>
                {% else %}
                <p class="product-price">R$ {{ product.price }}</p>
                {% endif %}
                <p class="text-justify">{{ product.description }}</p>
                <form action="{% url 'checkout:create_cart_item' product.slug %}" method="post">
                    {% csrf_token %}
                    {% if product.size.all %}
                    <div class="row">
                        <div class="col-md-6">
                            <label>Tamanho</label>
                            <select class="form-control mb-3" name="value_size">
                                {% for product in product.size.all %}
                                <option value="{{ product.name }}">{{ product.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {% endif %} 
                    <button class="product-button" type="submit">Comprar</button>
                </form>
            </div>
        </div>
    </div>
</div>  
{% endblock %}
    

catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% load static %}

{% load pagination %}

{% block title %}Produtos | {{ block.super }} {% endblock %}

{% block container %}
<div class="container div-content">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicío</a></li>
        <li class="breadcrumb-item active" aria-current="page">Produtos</li>
    </ol>
    <div class="d-flex justify-content-center">
        <h1 class="title-h1">Produtos</h1>
    </div>
    <div class="row div-distance">
        {% for product in product_list %}
        <div class="col-sm-6 col-lg-4 py-2">
            <div class="card h-100 border-0">
                <a href="{{ product.get_absolute_url }}">
                    {% if product.image %}
                    <img class="card-img rounded-0" src="{{ product.image.url }}" alt="Card image">
                    {% else %}
                    <img class="card-img rounded-0" src="{% static 'img/bg-product.png' %}" alt="Card image">
                    {% endif %}
                </a>
                <div class="card-body text-center">
                    <a class="card-title text-nowrap bd-highlight" style="width: 5rem;" href="{{ product.get_absolute_url }}">{{ product }}</a>
                    <div class="d-flex justify-content-around">
                        {% if product.sale %}
                        <p class="card-previous-price">R$ {{ product.price }}</p>
                        <p class="card-sale">R$ {{ product.sale }}</p>
                        {% else %}
                        <p class="card-price">R$ {{ product.price }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div> 
    {% pagination request paginator page_obj %}
</div>
{% endblock %}
   